import type { Metadata } from "next";
import { Spectral } from "next/font/google";
import "./globals.css";
import { Confetti } from "./components/Index";

const spectral = Spectral({
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${spectral.className} antialiased`}>
        <Confetti />
        {children}
      </body>
    </html>
  );
}
