import type { Metadata } from "next";
import { Spectral } from "next/font/google";
import "./globals.css";
import { Confetti } from "./components/Index";
import backgroundImage from "/public/images/backgrounds/maelle-bg.jpg";
import Image from "next/image";

const spectral = Spectral({
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${spectral.className} antialiased`}>
        <div className="fixed left-1/2 -translate-x-1/2 top-0 h-[1500px] w-full bg-black/70">
          <Image
            src={backgroundImage}
            alt="Background"
            fill
            className="object-contain opacity-70 mt-[48px]"
          />
        </div>
        <Confetti />

        {children}
      </body>
    </html>
  );
}
